name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  contents: read
  packages: write

jobs:
  package_publish:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: ğŸ”§ Restore & Build
        run: |
          dotnet restore "CSM Foundation Core/CSM Foundation Core/CSM Foundation Core.csproj"
          dotnet build   "CSM Foundation Core/CSM Foundation Core/CSM Foundation Core.csproj" \
            --configuration Release

      - name: ğŸ“¦ Pack NuGet project
        run: |
          dotnet pack "CSM Foundation Core/CSM Foundation Core/CSM Foundation Core.csproj" \
            --configuration Release \
            --output ./nupkgs
  
      - name: ğŸ“¤ Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PUBLISH_PAT }}
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $NUGET_AUTH_TOKEN \
            --skip-duplicate
